### ISSUE TITLE
0.5.1 not registered?

### ISSUE THREAD

**Issue by fonsp** [clarkevans/HypertextLiteral.jl#6]
This was today:

![image](https://user-images.githubusercontent.com/6933510/107260354-50bcd000-6a3e-11eb-9ad9-9025163a1d65.png)

**Comment by clarkevans** [comment]
It was a documentation only change.  I'll register it.

**Comment by fonsp** [comment]
Ah I see, thanks!

**Comment by clarkevans** [comment]
I've just registered v0.5.2 with the fix for #7 -- thank you.
